### ISSUE TITLE
Cannot launch project

### ISSUE THREAD

**Issue by Ricro** [krystalcampioni/vue-hotel-datepicker#231]
### Description

I cannot launch the development server due to an error related to @vue/cli-service.

```
TypeError: webpackConfig.devtool is not a function
    at /Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/commands/serve.js:54:12
    at /Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/commands/serve.js:75:31)
    at Service.run (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/laurentroy/Sites/vue-hotel-datepicker-custom/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

### Steps to Reproduce

1. git clone git@github.com:krystalcampioni/vue-hotel-datepicker.git
2. yarn install
3. yarn serve

**Expected behavior:** Development server launching and start coding.

**Actual behavior:** Error when launching dev server and can't code :(

I also tried with npm, reinstalled vue-cli-service but nothing worked.
I haven't found anything on the internet related to "webpackConfig.devtool is not a function". I guess that the issue comes from my local config (MacOS), but I couldn't find what. 
Thanks for your help!

### Datepicker Version

v3.0.10

**Comment by superbiche** [comment]
Hi @Ricro , 
It seems you have cloned the `main` branch which is not maintained anymore. We're launching v4.0.0 very soon and focus all efforts towards this release.

Could you try to `git checkout v4.0.0-dev` and re-run `yarn` and `yarn serve` ? It should be working correctly then.

Let me know how it goes.

**Comment by Ricro** [comment]
Hi @superbiche and thank you for your fast reply.

l cloned the main branch indeed, and the dev server works like a charm on v4.0.0-dev branch.

I also love the new features you are working on. Keep it up!
